### ISSUE TITLE
Global Styles

### ISSUE THREAD

**Issue by AlexRyzhkova** [AlexRyzhkova/MarryMe_App#12]
# User story
As a developer
I want to have a global basic styling  for my project
so I can easily choose and change styling in my App.

# Description

# Material

# Done?
- [x] Add basic fonts
- [x] Add basic colors
- [ ]
- [ ]

**Comment by marwinburesch** [comment]
Regarding your user story: if you have a space between the `#` and the word in markdown it formats headings correctly ;) 
`# Material` for example instead of `#Material` :P
